module.exports = {
  darkMode: "class",
  content: [
    "./_drafts/**/*.html",
    "./_includes/**/*.html",
    "./_layouts/**/*.html",
    "./_posts/*.md",
    "./*.md",
    "./*.html",
  ],
  theme: {
    extend: {
      colors: {
        /* --- Dark Mode Tokens --- */
        "surface": "#131314",
        "surface-dim": "#131314",
        "surface-bright": "#3a393a",
        "surface-container-lowest": "#0e0e0f",
        "surface-container-low": "#1c1b1c",
        "surface-container": "#201f20",
        "surface-container-high": "#2a2a2b",
        "surface-container-highest": "#353436",
        "surface-variant": "#353436",
        "on-surface": "#e5e2e3",
        "on-surface-variant": "#c2c6d4",
        "outline": "#8c909e",
        "outline-variant": "#424752",
        "primary": "#acc7ff",
        "primary-container": "#0056b3",
        "on-primary": "#002f67",
        "on-primary-container": "#bbd0ff",
        "primary-fixed-dim": "#acc7ff",
        "secondary": "#b3c7f1",
        "secondary-container": "#36496d",
        "on-secondary-container": "#a5b9e2",
        "inverse-surface": "#e5e2e3",
        "inverse-on-surface": "#313031",
        "inverse-primary": "#115cb9",
        /* --- Light Mode Overrides (via dark: prefix) --- */
        "light-surface": "#f9f9fb",
        "light-surface-container-low": "#f7f6f7",
        "light-surface-container-high": "#eceaeb",
        "light-surface-container-highest": "#e6e2e3",
        "light-on-surface": "#1c1b1c",
        "light-on-surface-variant": "#44474e",
        "light-primary": "#0056b3",
        "light-primary-container": "#d7e2ff",
        "light-outline": "#74777f",
        "light-outline-variant": "#c4c6d0",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        md: "12px",
        lg: "16px",
        xl: "24px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
